### ISSUE TITLE
What the heck is the event loop anyway

### ISSUE THREAD

**Issue by nearbycoder** [youearnedit/YEI-lunchnlearn#13]
Understanding how javascript works is a vital thing not just for the front-end but also for engineers on the backend using node. I would like to start having some more Javascript focused lunch in learns and this is a video that helped me understand how the event loop works in javascript.

https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by stripethree** [comment]
Watched on Nov. 6
