### ISSUE TITLE
React Hooks 

### ISSUE THREAD

**Issue by nearbycoder** [youearnedit/YEI-lunchnlearn#15]
React Hooks is a RFC for the next version of React 16.7. It provides a simpler API for functional stateful components and gives back control to allow for cross-component shared logic. I personally think it will be a game changer to how current React code is written and would like to know how the rest of the team feels about it.

https://www.youtube.com/watch?v=V-QO-KO90iQ

**Comment by stripethree** [comment]
Watched on Oct. 30!
