### ISSUE TITLE
All the Little Things by Sandi Metz

### ISSUE THREAD

**Issue by noahseger** [youearnedit/YEI-lunchnlearn#25]
https://www.youtube.com/watch?v=8bZh5LMaSmE (38:46)

> Theory tells us to build applications out of small, interchangeable objects but reality often supplies the exact opposite. Many apps contain huge classes of long methods and hair-raising conditionals; they're hard to understand, difficult to reuse and costly to change. This talk takes an ugly section of conditional code and converts it into a few simple objects. It bridges the gap between OO theory and practice and teaches straightforward strategies that all can use to improve their code.
>
> Sandi Metz, author of "Practical Object-Oriented Design in Ruby", believes in simple code and straightforward explanations. She prefers working software, practical solutions and lengthy bicycle trips (not necessarily in that order) and consults and teaches on all things OOP.

**Comment by stripethree** [comment]
Watched today!
