### ISSUE TITLE
The surprising ways in which developers can improve lives with playfulness and perspective

### ISSUE THREAD

**Issue by anDreaming** [youearnedit/YEI-lunchnlearn#31]
https://www.ted.com/talks/jane_mcgonigal_the_game_that_can_give_you_10_extra_years_of_life

Jane McGonigal speaks on the process behind her application "SuperBetter" and how we can use technology, games and otherwise, to live longer and better.

**Comment by stripethree** [comment]
Forgot to close this last week after we watched it, great talk!
