### ISSUE TITLE
Microservices + Events + Docker = A Perfect Trio

### ISSUE THREAD

**Issue by theaccordance** [youearnedit/YEI-lunchnlearn#32]
https://www.youtube.com/watch?v=sSm2dRarhPo

> Microservices are an essential enabler of agility but developing and deploying them is a challenge.
> In order for microservices to be loosely coupled,each service must have its own datastore.
> This makes it difficult to maintain data consistency across services.
> Deploying microservices is also a complex problem since an application typically consists of 10s or 100s of services, written in a variety of languages and frameworks.
> In this presentation, you will learn how to solve these problems by using an event-driven architecture to maintain data consistency and by using Docker to simplify deployment.

**Comment by stripethree** [comment]
Some related links from the discussion from today, after watching this video:

https://towardsdatascience.com/cap-theorem-and-distributed-database-management-systems-5c2be977950e

https://segment.com/blog/goodbye-microservices/
