### ISSUE TITLE
Authentication and Authorization in a Cloud and Microservice World by Stefan Reuter and Thomas Kruse

### ISSUE THREAD

**Issue by theaccordance** [youearnedit/YEI-lunchnlearn#33]
https://www.youtube.com/watch?v=g52hubmhUP4

This is a very thorough talk on implementing Authorization & Authentication standards and touches on B2B use cases that our product also shares, like Federated SSO, multiple apps, & permissions

**Comment by stripethree** [comment]
Watched on March 12
