### ISSUE TITLE
Code Smells in Ruby what Really are they

### ISSUE THREAD

**Issue by nearbycoder** [youearnedit/YEI-lunchnlearn#7]
This is a really great talk by Sandi Metz (My Ruby Idol) about code smells.

Get a Whiff of This by Sandi Metz
https://www.youtube.com/watch?v=PJjHfa5yxlU

Most code is a mess. Most new requirements change existing code. Ergo, much of our work involves altering imperfect code.

That's the bad news.

The good news is that every big mess consists of many small ones. Certain small problems occur so frequently that they've been given names, and are collectively known as "Code Smells".

This talk shows how to take a pile of perplexing code, identify the "smells", and surgically apply the curative refactorings. It breaks a messy problem into clear-cut pieces and proves that you can fix anything without being forced to understand everything.

**Comment by stripethree** [comment]
Watched on Oct. 9!

Code examples on the same concept but in JS, per @nearbycoder - https://elijahmanor.com/javascript-smells/

**Comment by stripethree** [comment]
Also related: https://www.industriallogic.com/blog/smells-to-refactorings-cheatsheet/
